services:
  - type: web
    name: limobile-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
