services:
  - type: web
    name: limobile-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src
